version: '3.9'

services:
  app:
    build: .
    container_name: weather_web_app
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pipeline_db
    ports:
      - "5432:5432"